server:
  port: 8761 #端口号

eureka:
  instance:
    hostname: localhost
  client:  #服务注册中心亦可作为客户端，设置不注册
    register-with-eureka: false #是否将当前的Eureka Server作为客户端进行注册
    fetch-registry: false #是否获取其他Eureka Server服务的数据
    serviceUrl:  #服务注册地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #注册中心的访问地址

spring:
  application:
    name: eureka-server



