
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: demo_zuul
zuul:
  routes:
    feign:
      path: /feign/** # 自定义的路由
      serviceId: acyx-feign # 指向的服务名称
