
server:
  port: 8081 #端口号

spring:
  application:
    name: demo_producer #当前服务注册在Eureka Server 上的名称

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #注册中心的访问地址
  instance:
    prefer-ip-address: true  #是否将当前服务的ip注册到Eureka-Server
